# Generated by Django 3.0.3 on 2020-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarNames',
            fields=[
                ('id', models.TextField(blank=True, db_column='Id', primary_key=True, serialize=False)),
                ('brand_name', models.TextField(blank=True, db_column='Brand_name', null=True)),
                ('model_link', models.TextField(blank=True, db_column='Model_Link', null=True)),
                ('model_name', models.TextField(blank=True, db_column='Model_name', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'db_table': 'car_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('engine_power', models.TextField(blank=True, db_column='engine power', null=True)),
                ('fuel_type', models.TextField(blank=True, db_column='fuel type', null=True)),
                ('gearbox', models.TextField(blank=True, null=True)),
                ('transmission', models.TextField(blank=True, null=True)),
                ('milage', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manufactories',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('company_link', models.TextField(blank=True, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manufactories',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Pisa',
        ),
    ]
